version: 0.2

phases:
  build:
    commands:
      - VERSION_NAME=just-flask
      - REPOSITORY_NAME=JuskFlask
      - 'ACCOUNT_ID=$(echo $CODEBUILD_BUILD_ARN | cut -d : -f 5)'
      - REPOSITORY=https://github.com/subhojitgit/JustFlask
      - VERSION=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - docker pull ${REPOSITORY}:latest || true
      - docker build --cache-from ${REPOSITORY}:latest -t ${REPOSITORY}:latest -t ${REPOSITORY}:${VERSION} .
      - docker push ${REPOSITORY}
      - 'printf ''{"repository": "%s", "version": "%s"}'' $REPOSITORY $VERSION > version.json'

artifacts:
  files:
    - version.json